/*
 * Partial Graph API No description provided (generated by Swagger Codegen
 * https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git Do not edit the class
 * manually.
 */

package msgraph.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.microsoft.graph.CollectionOfMessage;

/**
 * CollectionOfMessage with added count field
 */

public class CollectionOfMessageWithCount extends CollectionOfMessage {

  @JsonProperty("@odata.count")
  private Integer _count = null;

  public Integer getCount() {
    return _count;
  }

}
